lab02/encuesta/urls.py
from django.urls import path
from . import views

app_name = 'encuesta'

urlpatterns = [
    path ('', views.index, name='index'),
    path ('enviar',views.enviar, name = 'enviar'),
    path('resultados/', views.resultados, name='resultados'),
    path('volumenes/', views.volumenes, name='volumenes'),
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path ('encuesta/', include ('encuesta.urls')),
    path('admin/', admin.site.urls),
]

lab02/encuesta/models.py
from django.db import models

# Create your models here.

lab02/encuesta/views.py
from django.shortcuts import render
def index (request):
    context = {
        'titulo':"Formulario",
    }
    
    return render(request, 'encuesta/volumen.html',context)

def enviar (request):
    context = {
        'titulo' : "Respuesta",
        'nombre' : request.POST['nombre'],
        'clave' : request.POST['password'],
        'educacion' : request.POST['educacion'],
        'nacionalidad' : request.POST['nacionalidad'],
        'idiomas' : request.POST.getlist('idiomas'),
        'correo' : request.POST['email'],
        'website' : request.POST['sitioweb'],
    }
    return render (request, 'encuesta/respuesta.html', context)


def resultados(request):
    numero1 = int(request.POST.get('numero1'))
    numero2 = int(request.POST.get('numero2'))
    operacion = request.POST.get('operacion', '')
    
    if operacion == 'suma':
        resultado = numero1 + numero2
    elif operacion == 'resta':
        resultado = numero1 - numero2
    elif operacion == 'multiplicacion':
        resultado = numero1 * numero2
    else:
        resultado = 0
    
    context = {
        'titulo': "Resultado de la operación",
        'operacion': operacion,
        'numero1': numero1,
        'numero2': numero2,
        'resultado': resultado,
    }
    return render(request, 'encuesta/resultado.html', context)

def volumenes(request):
    if request.method == 'POST':
        diametro = float(request.POST.get('diametro'))
        altura = float(request.POST.get('altura'))
        radio = diametro / 2
        volumen = 3.14159265359 * (radio ** 2) * altura
        return render(request, 'encuesta/resultadoV.html', {'volumen': volumen})
    
  

lab02/encuesta/templates/encuesta/formulario.html
<h2> {{titulo}}</h2>
<form action="{% url 'encuesta:enviar' %}" method="post">
   {% csrf_token %}
    Nombre:
    <input type=" text" name="nombre" maxlength="50"><br>
    Contraseña:
    <input type="password" name="password"><br>
    Educacion:
    <select name = "educacion">
        <option value = "sin-estudios">Sin estudios</option>
        <option value = "educacion-obligatoria" selected="selected">Educación Obligatoria</option>    
        <option value = "formacion-profesional">Formación profesional</option>
        <option value = "unversidad">Universidad</option>
    </select><br>
    Nacionalidad:
    <input type="radio" name ="nacionalidad" value="hispana">Hispana</input>  
    <input type="radio" name ="nacionalidad" value="otra">Otra</input><br>
    Idiomas:
    <input type="checkbox" name="idiomas" value="español" checked="checked">Español</input>
    <input type="checkbox" name="idiomas" value="ingles" >Inglés</input> 
    <input type="checkbox" name="idiomas" value="frances" >Francés</input> 
    <input type="checkbox" name="idiomas" value="aleman" >Alemán</input><br>        
    Email:
    <input type="text" name="email"><br>
    Sitio Web:
    <input type="text" name="sitioweb"><br>
    <input type="submit" name="submit" value="Enviar">

</form>

lab02/encuesta/templates/encuesta/operaciones.html
<h2>Operaciones Matemáticas</h2>
<form action="{% url 'encuesta:resultados' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="numero1">Número 1:</label>
        <input type="number" class="form-control" id="numero1" name="numero1" required>
    </div>
    <div class="form-group">
        <label for="numero2">Número 2:</label>
        <input type="number" class="form-control" id="numero2" name="numero2" required>
    </div>
    <div class="form-group">
        <label for="operacion">Operación:</label>
        <select class="form-control" id="operacion" name="operacion">
            <option value="suma">Suma</option>
            <option value="resta">Resta</option>
            <option value="multiplicacion">Multiplicación</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Calcular</button>
</form>

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{titulo}}</h2>
<p>Nombre: {{nombre}}</p>
<p>Clave: {{clave}}</p>
<p>Educacion: {{educacion}}</p>
<p>Nacionalidad: {{nacionalidad}}</p>
<p>Idiomas: </p>
<ul>
    {% for item in idiomas%}
    <li>{{item}}</li>
    {%endfor%}
</ul>
<p>Email:{{correo}}</p>
<p>Sitio Web: {{website}}</p>

lab02/encuesta/templates/encuesta/resultado.html
<h2>Resultado de la operacion:</h2>
<p>La {{ operacion }} de {{ numero1 }} + {{ numero2 }} = {{ resultado }}</p>

lab02/encuesta/templates/encuesta/resultadoV.html
<h1>Resultado del Cálculo</h1>
<p>El volumen del cilindro es: {{ volumen }} metros cúbicos.</p>

lab02/encuesta/templates/encuesta/volumen.html
<h2>Calcular Volumen de Cilindro</h2>
<form action="{% url 'encuesta:volumenes' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="diametro">Introduzca el diámetro en metros:</label>
        <input type="number" class="form-control" id="diametro" name="diametro" required step="0.01" inputmode="decimal">
    </div>
    <div class="form-group">
        <label for="altura">Introduzca la altura en metros:</label>
        <input type="number" class="form-control" id="altura" name="altura" required step="0.01" inputmode="decimal">
    </div>
    <button type="submit" class="btn btn-primary">Calcular</button>
</form>